repositories:
- name: metallb
  url: https://metallb.github.io/metallb
- name: hashicorp
  url: https://helm.releases.hashicorp.com

releases:
- name: metallb
  namespace: metallb
  createNamespace: true
  chart: metallb/metallb
  version: 0.15.3

- name: vault
  namespace: vault
  createNamespace: true
  chart: hashicorp/vault
  version: 0.31.0

- name: vault-secrets-operator
  namespace: vault-secrets-operator
  createNamespace: true
  chart: hashicorp/vault-secrets-operator
  version: 1.0.1
